(() => {
  'use strict';
  const G = window.STORY, $ = id => document.getElementById(id), KEY = 'life2003.v2';
  const clone = v => JSON.parse(JSON.stringify(v));
  const empty = () => ({ version:2, auto:null, slots:[null,null,null], unlocked:{}, seen:[], compact:false });
  let db = empty(), s = null, screen = 'title', storageOK = true, toastTimer;
  const backend=window.GAME_BACKEND||{enabled:false,contentVersion:0};
  const editionTag=`build-${backend.buildId||'static'}/content-${backend.contentVersion}`;
  let visitSession;
  if(backend.enabled){try{visitSession=sessionStorage.getItem('life2003.visit')||crypto.randomUUID();sessionStorage.setItem('life2003.visit',visitSession);}catch{visitSession=crypto.randomUUID();}}
  function track(kind,node,choice,label){if(!backend.enabled)return;fetch('/api/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,node,choice,label,session:visitSession,edition:editionTag}),keepalive:true}).catch(()=>{});}
  const resolve = v => typeof v === 'function' ? v(s) : v;
  const valid = x => x && (G.nodes[x.node]||G.legacyNodeIds.includes(x.node)) && Number.isFinite(x.year) && x.year >= 2018 && x.year<=2100 && Number.isFinite(x.cash) && x.cash >= 0 && x.cash<=1e9 && Number.isFinite(x.debt) && x.debt >= 0 && x.debt<=1e9 && ['learn','study','family'].every(k=>Number.isFinite(x[k])) && x.flags && typeof x.flags === 'object' && !Array.isArray(x.flags) && Array.isArray(x.wishes) && x.wishes.every(w=>w&&Number.isFinite(w.age)&&typeof w.text==='string') && Array.isArray(x.history) && x.history.every(id=>typeof id==='string');
  try {
    const raw=localStorage.getItem(KEY);
    if(raw){const data=JSON.parse(raw);if(data.version===2){db={...empty(),...data};db.slots=Array.from({length:3},(_,i)=>valid(data.slots?.[i]?.state)?data.slots[i]:null);db.auto=valid(data.auto?.state)?data.auto:null;db.unlocked=data.unlocked&&typeof data.unlocked==='object'?data.unlocked:{};db.seen=Array.isArray(data.seen)?data.seen.filter(x=>typeof x==='string'):[];}}
  } catch { storageOK=false; }
  function persist(){try{localStorage.setItem(KEY,JSON.stringify(db));storageOK=true;}catch{storageOK=false;} $('save-status').textContent=storageOK?'已保存到此浏览器':'无法持久保存 · 请导出备份';}
  function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2800);}
  function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
  function btn(label,fn,cls='choice',index){const b=el('button',undefined,cls);if(index!==undefined)b.append(el('span',String(index+1).padStart(2,'0'),'key'));b.append(el('span',label));b.onclick=fn;return b;}
  function content(parent,body,quote){for(const text of body||[])parent.append(el('p',text));if(quote)parent.append(el('blockquote',quote));}
  function resetMain(){const m=$('main');m.replaceChildren();m.focus({preventScroll:true});window.scrollTo(0,0);return m;}
  function count(){return G.endings.filter(id=>!!db.unlocked[id]).length;}
  function header(m){const t=el('div',undefined,'time'),left=el('div'),year=el('div',String(s.year),'year');year.append(el('span',`${s.year-2003}岁`,'age'));left.append(year,el('div',s.role,'identity'));const funds=el('div',`¥ ${s.cash.toLocaleString('zh-CN')}`,'money');const help=btn('?',()=>dialog('手里的钱',box=>content(box,['这里是现在能用的现金，不是工资总额。','开局537元是这份虚构故事给定的零用积蓄，不是你已经挣到的奖励，也不是作者真实存款。','后来只在收款实际到账时增加。库存、车辆、押金、待收款不当成手里的钱；借款另记。','每一笔来去可在「收支账本」看。'])),'money-help');help.setAttribute('aria-label','查看现金和开局537元的说明');funds.append(help);if(s.debt)funds.append(el('div',`未还 ¥ ${s.debt.toLocaleString('zh-CN')}`,'debt'));t.append(left,funds);m.append(t);}
  function painting(parent,id,ending=false){const n=G.nodes[id],art=G.artFor(id),tile=n.sprite?.tile??art%16,atlas=n.sprite?.atlas;const wrap=el('figure',undefined,ending?'pixel-frame ending-painting':'pixel-frame event-painting');const scene=el('div',undefined,'pixel-scene');const items=['酒瓶','坏眼镜','零花钱罐','卫生巾与课本','费用纸与旧校服','手机消息','货物纸箱','电影票','检查单','奖状','工牌','口红','项目电脑','车钥匙与账单','方便面','婚礼喜糖'];const label=n.sprite?items[tile]:(ending?`${n.title}的生活物件`:'生活物件');scene.setAttribute('role','img');scene.setAttribute('aria-label',label+'的低像素画');const artSheet=ending?(id==='end_award'?'atlas-a':`atlas-v5-${['a','b','c'][Math.floor(art/16)]}`):`atlas-${['a','b','c'][Math.floor(art/16)]}`;scene.style.backgroundImage=n.image?`url(${n.image})`:atlas?`url(assets/${atlas}.png)`:`url(assets/${artSheet}.png)`;scene.style.backgroundPosition=n.image?'center':`${(tile%4)*100/3}% ${Math.floor(tile/4)*100/3}%`;scene.style.backgroundSize=n.image?'cover':'';wrap.append(scene);if(!ending)wrap.append(el('figcaption',resolve(n.object)||label));parent.append(wrap);}
  function stamp(){return {state:clone(s),at:Date.now()};}
  function autosave(){db.auto=stamp();persist();}
  function enter(id){let n,hops=0;do{n=G.nodes[id];if(!n)throw new Error('未找到剧情');const oldYear=s.year;s.node=id;s.year=typeof n.year==='function'?n.year(s):(n.year||s.year);if(s.year<oldYear)throw Error('剧情年份倒退');s.role=G.roleFor?G.roleFor(s,n):n.role||s.role;const first=!s.history.includes(id);s.history.push(id);if(n.enter&&first)n.enter(s);if(n.roleFor)s.role=G.roleFor(s,n);if(!n.route)break;id=n.route(s);if(++hops>20)throw new Error('剧情连接异常');}while(true);if(n.ending&&!db.unlocked[id])db.unlocked[id]={at:Date.now(),snapshot:clone(s)};autosave();render();}
  function available(){return G.available(s);}
  function choose(index){if(screen!=='game'||$('panel').open)throw new Error('请先回到当前剧情');const c=available()[index];if(!c)throw new Error('该选项当前不可用');track('choice',s.node,index,c.label);if(available().length>1){const snap=clone(s);snap.checkpoints=[];s.checkpoints.push({state:snap,label:`${s.year} · ${s.role}`,choice:c.label});s.checkpoints=s.checkpoints.slice(-12);}G.apply(s,c.effects);enter(c.to);}
  function newRun(){s=G.fresh();screen='game';enter('birth');}
  function confirmNew(){newRun();}
  function title(){screen='title';const m=resetMain();m.className='title-page';m.append(el('p','2018 / 十五岁 / 中考前','eyebrow'),el('div','2003','number'),el('h1','基层女性模拟器'),el('p','家里四个孩子。\n两个姐姐，你，一个弟弟。','intro'));const cs=el('div',undefined,'choices');if(db.auto)cs.append(btn('继续上一次',()=>load(db.auto),'choice primary'));cs.append(btn(db.auto?'重新开始':'开始',confirmNew,'choice primary'),btn('存档 / 读档',saves),btn(`结局档案  ${count()} / ${G.endings.length}`,archive));m.append(cs,el('p','一局是一段人生，不必走完一生。\n虚构故事；金额是剧情参数。未来年份是推演。\n存档只在此浏览器，可导出。含家庭暴力、怀孕危机与劳动困境。','note'));$('save-status').textContent=storageOK?'本机存档':'无法持久保存 · 请导出备份';}
  function render(){screen='game';const n=G.nodes[s.node],m=resetMain();m.className=n.ending?'ending':'';header(m);track('node_view',n.id);if(n.ending)track('ending',n.id);const body=resolve(n.body),quote=resolve(n.quote),key=JSON.stringify([n.id,body,quote]);const wasRead=db.seen.includes(key);if(!wasRead){db.seen.push(key);persist();}
    if(n.ending){painting(m,n.id,true);m.append(el('div',`结局 ${String(G.endings.indexOf(n.id)+1).padStart(2,'0')}`,'ending-label'),el('h1',`《${n.title}》`));}
    // Reading history must never hide story on entry, refresh, or loading a save.
    const b=el('div',undefined,'body');content(b,body,quote);m.append(b);
    if(!n.ending)painting(m,n.id);
    if(n.ending){
      if(s.wishes.length){const ws=el('div',undefined,'wish-list');for(const w of s.wishes){const line=el('div');line.append(el('span',`${w.age}岁`),document.createTextNode(w.text));ws.append(line);}m.append(ws);}
      const progress=el('div',undefined,'collection-progress');progress.append(document.createTextNode('本版共有 '+G.endings.length+' 个结局。\n'),el('strong',`你已解锁 ${count()} / ${G.endings.length} 个`));m.append(progress);
      const cs=el('div',undefined,'choices');cs.append(btn('再来一次',newRun,'choice primary'),btn('回到分岔，换一个选择',branches),btn('查看结局档案',archive));m.append(cs);
    }else{const cs=el('div',undefined,'choices');available().forEach((c,i)=>cs.append(btn(c.label,()=>choose(i),'choice',i)));m.append(cs);}
    const actions=el('div',undefined,'scene-actions');actions.append(btn('存档 / 读档',saves,'quiet'),btn('收支账本',ledger,'quiet'));if(backend.enabled)actions.append(btn('反馈这段剧情',feedback,'quiet'));if(wasRead&&!n.ending){const fold=btn('收起本页文字',()=>{const collapsed=b.classList.toggle('compact');fold.querySelector('span').textContent=collapsed?'展开本页文字':'收起本页文字';fold.setAttribute('aria-expanded',String(!collapsed));},'quiet');fold.setAttribute('aria-expanded','true');actions.append(fold);}m.append(actions);
  }
  function feedback(){dialog('反馈这段剧情',box=>{box.append(el('p',`关于《${G.nodes[s.node].title||s.node}》。不需要填写姓名或联系方式。`));const type=el('select');for(const [value,label] of [['story','剧情和文字'],['bug','运行问题'],['other','其他']]){const option=el('option',label);option.value=value;type.append(option);}const note=el('textarea');note.maxLength=1500;note.placeholder='哪一句、哪一个选择或哪段体验让你想反馈？';box.append(type,note,btn('提交反馈',async()=>{if(note.value.trim().length<3){toast('请至少写三个字');return;}try{const res=await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({node:s.node,edition:editionTag,category:type.value,message:note.value})});if(!res.ok)throw Error();close();toast('反馈已收到，谢谢你');}catch{toast('提交失败，请稍后再试');}}));});}
  function dialog(name,fill){$('panel-title').textContent=name;$('panel-content').replaceChildren();fill($('panel-content'));if(!$('panel').open)$('panel').showModal();}
  function close(){$('panel').close();}
  function load(slot){if(!valid(slot?.state)){toast('这个存档暂时无法读取');return;}const migrated=slot.state.edition!==G.edition;s=G.restore(clone(slot.state));close();autosave();render();if(migrated)toast('旧进度接到相应新版场景；原有的钱和结局还在');}
  function branches(){dialog('回到分岔',box=>{content(box,['只回到这次人生真实经历过的选择。已收集结局保留。']);const points=s?.checkpoints||[];if(!points.length){box.append(el('p','这份旧存档还没有分岔记录，可以读取手动档。'));box.append(btn('存档 / 读档',saves));return;}points.slice().reverse().forEach(p=>box.append(btn(`${p.label} · 当时选了「${p.choice}」`,()=>load({state:p.state}))));});}
  function ledger(){dialog('收支账本',box=>{box.append(el('p',`可用现金 ¥${s?.cash.toLocaleString('zh-CN')||0} · 未还债务 ¥${s?.debt.toLocaleString('zh-CN')||0}`));box.append(el('p','工资为剧情参数。已到账、待收款、借款和资产不是一回事。','note'));for(const t of (s?.ledger||[]).slice(-40)){box.append(el('p',`${t.year} · ${t.label}\n现金 ${t.cash>=0?'+':''}${t.cash} / 债务 ${t.debt>=0?'+':''}${t.debt}`,'ledger-row'));}if(!s?.ledger?.length)box.append(el('p','旧版本没有逐笔账本；从新版后续收支开始记录。'));});}
  function saves(){dialog('存档 / 读档',box=>{
    box.append(el('p','读档可以重选。已解锁的结局会保留。','muted'));
    [db.auto,...db.slots].forEach((slot,i)=>{const row=el('div',undefined,'slot');row.append(el('div',i===0?'自动存档':`手动存档 ${i}`,'slot-title'));row.append(el('div',slot?`${slot.state.year} / ${slot.state.year-2003}岁 / ${slot.state.role}\n${new Date(slot.at).toLocaleString('zh-CN')}`:'空','slot-meta'));const buttons=el('div',undefined,'slot-buttons');if(slot)buttons.append(btn('读取',()=>load(slot),'small-btn'));if(i>0){const save=btn('存到这里',()=>{const current=s||db.auto?.state;if(!current)return;if(db.slots[i-1]){dialog('覆盖这个手动存档？',b=>{content(b,['原来的这一格会被替换。']);b.append(btn('覆盖',()=>{db.slots[i-1]={state:clone(current),at:Date.now()};persist();saves();toast(storageOK?'已存档':'已在本次页面暂存，请导出备份');}),btn('取消',saves));});}else{db.slots[i-1]={state:clone(current),at:Date.now()};persist();saves();toast(storageOK?'已存档':'已在本次页面暂存，请导出备份');}},'small-btn');save.disabled=!(s||db.auto);buttons.append(save);}row.append(buttons);box.append(row);});
    const tools=el('div',undefined,'slot-buttons');tools.append(btn('导出备份',exportSave,'small-btn'),btn('导入备份',importSave,'small-btn'));box.append(el('p','更换设备或清理浏览器前，可以导出备份。','note'),tools);
  });}
  function archive(){dialog(`结局档案 · ${count()} / ${G.endings.length}`,box=>{box.append(el('p','未解锁的名字，等走到那里再看。','muted'));const list=el('div',undefined,'endings');G.endings.forEach((id,i)=>{const unlocked=db.unlocked[id],row=el(unlocked?'button':'div',undefined,`ending-row${unlocked?'':' locked'}`);row.append(el('span',String(i+1).padStart(2,'0'),'index'),el('span',unlocked?`《${G.nodes[id].title}》`:'？？？'));if(unlocked){row.append(el('span','已解锁','date'));row.onclick=()=>{const n=G.nodes[id],saved=s;s=unlocked.snapshot||s;const body=resolve(n.body),quote=resolve(n.quote);s=saved;dialog(n.title,b=>{painting(b,id,true);content(b,body,quote);b.append(btn('返回结局档案',archive));});};}list.append(row);});box.append(list,el('p','这里统计本版可到达的结局。后续更新会扩充。','note'));});}
  function menu(){dialog('暂停',box=>{const ls=el('div',undefined,'menu-list');ls.append(btn('回到游戏',close),btn('存档 / 读档',saves),btn('回到这次人生的分岔',branches),btn('收支账本',ledger),btn(`结局档案 ${count()} / ${G.endings.length}`,archive),btn('创作与资料说明',sources),btn('回到标题页',()=>{close();title();}));box.append(ls);});}
  function sources(){dialog('创作与资料说明',box=>{content(box,['这是复合虚构人物，不是某位新闻当事人的传记。学校、岗位和情节不代表群体特征。','金额与结果采用剧情参数，不是行业行情、税务、医学、签证或投资指南。十五岁非法用工情节明确违法，不提供绕过年龄核验的方法。','新局固定一组外部事件，读档不会重抽；不是社会发生率。玩家的学习、资格、现金、关系和实际动作仍影响接下来能做什么。','学业按2018入学、专科三年、本科四年安排；复读或升本另加时间。弟弟暂按2005年出生。跳过的年份不把未描述的工资冒作已到账。','日本照护工作按公开资料作一个虚构样本；未来申请仍需核当时要求。医美和冻卵目前只写咨询，不提供具体手术或疗效。','复古马赛克画为AI生成原创素材，不是当事人照片。原作者两段日记保持原文。公开资料支持部分背景，不证明每个补写的故事。']);for(const [label,url] of [['中职免学费与资助条件 · 教育部2018','https://www.moe.gov.cn/jyb_xxgk/xxgk_jyta/jyta_zcs/201802/t20180228_328170.html'],['禁止使用童工规定','https://www.moe.gov.cn/jyb_xxgk/gk_gbgg/moe_0/moe_8/moe_30/tnull_337.html'],['币市2024剧情的政策背景 · 人民银行2021','https://www.pbc.gov.cn/tiaofasi/144941/3581332/4348658/index.html'],['日本照护领域特定技能 · 厚生劳动省','https://www.mhlw.go.jp/stf/newpage_000117702.html'],['特定技能申请资料 · 出入国在留管理厅','https://www.moj.go.jp/isa/applications/status/specifiedskilledworker'],['Vibe Coding 名称背景','https://cloud.google.com/discover/what-is-vibe-coding']]){const a=el('a',label,'source-link');a.href=url;a.target='_blank';a.rel='noopener noreferrer';box.append(a);}});}
  function exportSave(){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='2003-存档备份.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function importSave(){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{try{const file=input.files[0];if(!file)return;if(file.size>5000000)throw Error();const data=JSON.parse(await file.text());if(data.version!==2||!Array.isArray(data.slots)||data.slots.length!==3||!data.unlocked||!Array.isArray(data.seen))throw Error();if(data.auto&&!valid(data.auto.state))throw Error();if(data.slots.some(x=>x&&!valid(x.state)))throw Error();for(const [id,x]of Object.entries(data.unlocked)){if(!G.endings.includes(id)||!valid(x.snapshot))throw Error();}dialog('导入这份备份？',box=>{content(box,['会替换当前自动存档和三个手动存档。两份记录中已解锁的结局会合并。']);box.append(btn('导入',()=>{db={...empty(),...data,unlocked:{...db.unlocked,...data.unlocked},seen:[...new Set([...db.seen,...data.seen.filter(x=>typeof x==='string')])]};s=db.auto?clone(db.auto.state):null;persist();close();title();toast('备份已导入');}),btn('取消',saves));});}catch{toast('未能读取备份；原有存档没有改变');}};input.click();}
  $('menu-button').onclick=menu;$('close-panel').onclick=close;$('home-link').onclick=e=>{e.preventDefault();title();};$('panel').addEventListener('click',e=>{if(e.target===$('panel')){const r=$('panel').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close();}});
  document.addEventListener('keydown',e=>{if(screen==='game'&&!$('panel').open&&/^[1-4]$/.test(e.key)&&!e.repeat){const index=Number(e.key)-1;if(available()[index]){e.preventDefault();choose(index);}}});
  function publicState(){return {screen,year:s?.year,age:s?s.year-2003:null,identity:s?.role,cash:s?.cash,choices:screen==='game'&&s?available().map((c,i)=>({index:i,label:c.label})):[],unlocked:count(),total:G.endings.length};}
  if(document.modelContext?.registerTool){const life=new AbortController();for(const tool of [{name:'read_current_game',description:'Read the visible game state without revealing hidden story conditions.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>publicState()},{name:'choose_current_option',description:'Choose one currently visible story option by its zero-based index. Advances the game and autosaves.',inputSchema:{type:'object',properties:{index:{type:'integer',minimum:0}},required:['index'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!Number.isInteger(input?.index))throw Error('无效选项');choose(input.index);return publicState();}}]){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}}window.addEventListener('pagehide',()=>life.abort(),{once:true});}
  title();
})();
