/* Plot data is separate from rendering. Years always match a 2003 birth. */
(() => {
  const nodes = {}, endings = [];
  const C = (label, to, effects = {}, when = null) => ({ label, to, effects, when });
  const N = (id, year, role, body, choices, extra = {}) => nodes[id] = { id, year, role, body, choices, ...extra };
  const E = (id, year, title, body, extra = {}) => {
    endings.push(id); N(id, year, '', body, [], { ending: true, title, ...extra });
  };
  const fresh = () => ({ node: 'birth', year: 2018, role: '初三', cash: 537, debt: 0, study: 0, learn: 0, family: 0, flags: { school_rotation: Math.floor(Math.random() * 5) }, wishes: [], history: [] });
  function apply(s, effects) {
    if (typeof effects === 'function') return effects(s);
    for (const k of ['cash','debt','study','learn','family']) s[k] += effects[k] || 0;
    Object.assign(s.flags, effects.flags || {});
    if (effects.wish) s.wishes.push({ age: s.year - 2003, text: effects.wish });
  }
  const has = (s, tag) => !!s.flags[tag];
  const college = s => has(s,'college') || has(s,'private') || has(s,'university');
  const creative = s => college(s) && has(s,'computer') && has(s,'creator') && s.learn >= 2 && s.debt < 30000 && !has(s,'caregiver');
  const settledSister = s => has(s,'settled_sister') || s.history.includes('sister_stay');
  const schoolScenes = ['period_need','canteen_small','glasses_tape','phone_crack','uniform_small'];
  function nextSchoolScene(s) {
    const visited = schoolScenes.filter(id => s.history.includes(id));
    if (visited.length >= 3) return has(s,'sister_short') ? 'fee_other' : 'money';
    const rotation = Number.isInteger(s.flags.school_rotation) ? s.flags.school_rotation : 0;
    return [...schoolScenes.slice(rotation),...schoolScenes.slice(0,rotation)].find(id => !visited.includes(id));
  }
  N('birth',2018,'初三',['你出生于2003年。','山河四省的一个县城乡镇。\n家里四个孩子。\n两个姐姐，你，一个弟弟。','父亲常喝酒。也常不回家。\n母亲在厂里做零工。\n两个姐姐都已经出去挣钱。'],[C('往下','wish15')]);
  N('wish15',2018,'初三',['你十五岁。','你以后想过什么样的日子？'],[C('有钱','father',{wish:'有钱'}),C('离开这里','father',{wish:'离开这里'}),C('有一个自己的家','father',{wish:'有一个自己的家'}),C('不知道','father',{wish:'不知道'})]);
  N('father',2018,'初三',['晚上。\n爸爸喝醉回来。','厨房里有东西摔碎。\n弟弟把门锁上了。','你的手机亮了一下。'],[C('给那个男生发消息','noodles',{flags:{friend:true}}),C('去姐姐那里','sister',{flags:{sister:true}}),C('躲在房间里','morning'),C('去拦','morning',{flags:{intervened:true}})]);
  N('noodles',2018,'初三',['他给你煮方便面。','只有一包。\n他把鸡蛋给你。','你在他家写完作业。\n回去的时候，他送你到路口。'],[C('和他在一起','love',{flags:{love:true}}),C('只做朋友','morning'),C('以后不麻烦他了','morning',{flags:{friend:false}})],{object:'一包方便面'});
  N('love',2018,'初三',['后来你又去过几次。\n他一直给你留着一副筷子。','他也快毕业了。'],[C('跟他去县城','love_work',{flags:{left_school:true}}),C('我想继续读书','morning')],{quote:'“以后我们一起挣钱吧。”'});
  N('love_work',2019,'县城餐馆帮工',['没有上高中。\n你们租了一间屋。','他在后厨，你在前厅。\n月底交房租的时候，两个人坐着算钱。'],[C('再找一份周末工','love_second_year',{flags:{parttime:true}}),C('先把这份工作做稳','love_second_year')]);
  N('love_second_year',2020,'县城打工',s=>['他换到了另一家餐馆。\n你还在原来的店。',has(s,'parttime')?'周末也去上班。\n你们有时两天见不到面。':'晚上回来，两个人轮着做饭。','交完房租，还剩下一点。'],[C('存起来','love_third_year',{flags:{love_saved:true}}),C('去问还能不能继续学','love_third_year',{learn:1,flags:{love_selfstudy:true}})]);
  N('love_third_year',2021,'县城打工',['你们换过几份工作。\n菜还是一起买。','那天停电。\n锅里只剩一包方便面。','他把火点上了。'],[C('把碗递给他','end_noodles'),C('一起去别的城市看看','work_savings',{flags:{love_together:true}})]);
  E('end_noodles',2021,'两个人的方便面',['他没有变坏。\n只是也没有很多钱。','你终于有了一个不会打你的家。']);
  N('sister',2018,'初三',['姐姐让你进门。\n给你热了一碗饭。','她明天上早班。\n水池里还有几个碗。'],[C('住一晚，明天去学校','morning',{flags:{sister_short:true}}),C('想一直住在这里','sister_stay',{flags:{settled_sister:true,left_school:true}}),C('还是回去','morning')],{quote:'“你住可以，但我养不起闲人。”'});
  N('morning',2018,'初三',s=>[has(s,'intervened')?'早上，手臂还有点疼。':has(s,'sister_short')?'姐姐上班前给你留了一小袋馒头。':'第二天照常上学。','早读铃响了。\n你把书摊开。'],[C('进教室','school_pool')]);
  N('school_pool',2018,'初三',[],[],{route:nextSchoolScene});
  N('period_need',2018,'初三',['上课铃响前，月经来了。','书包里没有卫生巾。\n小卖部还没开门。'],[C('问同桌借一片','school_pool',{flags:{classmate:true,period_help:true}}),C('去办公室问女老师','school_pool',{flags:{teacher_help:true,period_help:true}}),C('先用纸垫着，上完这节课','school_pool',{study:-1,flags:{period_wait:true}}),C('给姐姐发消息','school_pool',{flags:{period_sister:true}},s=>has(s,'sister'))],{object:'一张折起来的纸'});
  N('canteen_small',2018,'初三',['饭卡里只剩三块七。','你在窗口前看了一会儿价目表。'],[C('买最便宜的那份','school_pool',{flags:{small_lunch:true}}),C('找同学借一点','school_pool',{flags:{classmate:true,lunch_owed:true}}),C('先去上课','school_pool',{study:-1,flags:{hungry:true}})]);
  N('glasses_tape',2018,'初三',['眼镜腿断了。\n胶带缠了两圈，还能戴。','黑板左边的字有点模糊。'],[C('先这样戴','school_pool',{flags:{broken_glasses:true}}),C('去问修眼镜要多少钱','school_pool',{flags:{glasses_quote:true}}),C('找老师换到前排','school_pool',{flags:{teacher_help:true,front_row:true}})]);
  N('phone_crack',2018,'初三',['手机屏幕裂了。','班级群的缴费通知，你昨晚才看清。'],[C('借同学手机看清','school_pool',{flags:{classmate:true,fee_notice:true}}),C('自己去问老师','school_pool',{flags:{teacher_help:true,fee_notice:true}}),C('先放着','school_pool',{flags:{late_notice:true}})]);
  N('uniform_small',2018,'初三',['校服小了。','袖口洗过很多次，颜色还是不一样。'],[C('照常穿','school_pool'),C('问问有没有旧校服','school_pool',{flags:{asked_uniform:true}}),C('那天不去排队','school_pool',{flags:{missed_notice:true}})]);
  N('sister_stay',2018,'借住姐姐家',['你早上做饭。\n晚上洗她的工作服。','姐姐回来得很晚。\n在桌上给你留了一份饭。'],[C('把这些活接下来','sister_marriage'),C('告诉姐姐，我也要挣钱','sister_job_offer'),C('我不想天天干这些','sister_tension')]);
  N('sister_tension',2018,'姐姐家',['姐姐下了夜班。\n水池里的碗还在。','“我自己都活不下去了。”'],[C('今天把活补上','sister_marriage',{flags:{sister_repaired:true}}),C('走','sister_outside',{flags:{sister_strained:true}})]);
  N('sister_marriage',2019,'姐姐家的帮手',['姐姐结婚了。','姐夫把鞋柜往外挪了一点。\n好放你的折叠床。','下个月房租又涨了。'],[C('继续帮姐姐干活','sister_child'),C('去工作，自己付房租','sister_job_offer'),C('找别的住处','sister_outside')]);
  N('sister_child',2021,'姐姐家的帮手',['姐姐生了孩子。\n没多久又回去上班。','孩子半夜哭，你比她先醒。'],[C('继续照顾孩子','end_second_mother',{flags:{caregiver:true}}),C('请姐姐介绍工作','bathhouse'),C('搬走，自己找工作','work_savings',{flags:{service:true}})]);
  N('sister_job_offer',2019,'找工作',['姐姐说，洗浴会所前台缺人。','登记、收银、接电话、倒水。\n还要排夜班。'],[C('去上一个月','bathhouse_early'),C('去餐馆问问','sister_other_work'),C('先留在姐姐家帮忙','sister_wait')]);
  N('sister_wait',2020,'姐姐家的帮手',s=>[s.history.includes('sister_marriage')?'姐姐和姐夫都要上班。':'后来姐姐结了婚。\n姐夫也要上班。','做饭、洗衣、跑腿。\n你继续住在折叠床上。'],[C('继续帮忙','sister_child'),C('还是出去工作','bathhouse')]);
  N('bathhouse_early',2019,'洗浴会所前台',['第一个月工资发下来了。\n三千多。','姐姐问你吃不吃宵夜。','你第一次觉得，不上学也能挣钱。'],[C('继续做前台','service_years',{flags:{service:true}}),C('攒钱搬出去','service_years',{flags:{service:true,own_room:true}})],{enter:s=>{s.cash+=3200;},object:'前台的号码牌'});
  N('sister_other_work',2019,'县城帮工',['餐馆的老板让你先端盘子。','每天站到晚上九点。\n月底结了工资。'],[C('继续做','service_years',{flags:{service:true}}),C('换个地方','service_years',{flags:{service:true,own_room:true}})],{enter:s=>{s.cash+=1800;}});
  N('service_years',2021,'服务业打工',['干了两年。','收银、交接、夜班。\n你已经知道工资哪天到账。'],[C('继续攒钱','work_savings',{flags:{service:true}}),C('问别的店有没有位置','work_savings',{flags:{service:true}})]);
  N('sister_outside',2019,'找住处',['姐姐家不能再住。','你提着袋子，在路边看招聘纸。'],[C('找普通工作','sister_other_work',{flags:{sister_strained:true}}),C('给那个男生发消息','boy_shelter_after_sister'),C('先回父母家','sister_other_work',{flags:{family_return:true}})]);
  N('boy_shelter_after_sister',2019,'临时住处',['他下班后赶过来。','给你找了一间能住几晚的房。\n第二天还得去上班。'],[C('去找工作','sister_other_work',{flags:{friend:true}})]);
  N('bathhouse',2021,'洗浴会所前台',['收银。登记。接电话。\n倒水。夜班。','第一个月工资3200。\n姐姐问你吃不吃宵夜。','你们在门口坐了一会儿。'],[C('继续做，攒钱','work_savings',{flags:{service:true}}),C('找别的服务业工作','work_savings',{flags:{service:true}})],{enter:s=>{s.cash+=3200;},object:'前台的号码牌'});
  N('fee_other',2018,'初三',['姐姐说，她可以帮你问问学校有没有资助。','班主任又发来一张中考报名表。\n你把要交的材料写在本子上。'],[C('先把表填好','income',{study:1}),C('去问老师资助怎么申请','income',{learn:1,flags:{teacher_help:true}})]);
  N('money',2018,'初三',['过年收到的500块，还在你手里。','资料费还差一些。\n妈妈说，弟弟要补课。','“你是姐姐。”'],[C('把500给她','income',{cash:-500,family:1,flags:{gave500:true}}),C('藏进旧棉袄','income',{cash:-500,flags:{stash:true}}),C('说这是我的资料费','income',{flags:{boundary:true}}),C('问姐姐借一点','income',{flags:{sister_debt:true}},s=>has(s,'sister'))],{object:'五张一百块'});
  N('income',2018,'初三',['周末。\n你还得上课。','朋友圈有人卖面膜。\n班群里有人发兼职。'],[C('问问怎么做代理','micro'),C('试试一单5块的兼职','scam_first'),C('去餐馆端盘子','after_school',{cash:120,study:-1,flags:{parttime:true}}),C('先把不会的题查完','after_school',{study:1,learn:1})]);
  N('micro',2018,'初三',['你替她发了几条朋友圈。\n真的卖出去两单。\n提成30。','她说，你很适合做生意。'],[C('交399，拿代理价','micro_stock',{cash:-399,flags:{micro:true}},s=>s.cash>=399),C('问姐姐借钱升级','micro_stock',{debt:1999,flags:{micro:true,micro_upgrade:true,sister_debt:true}},s=>has(s,'sister')),C('就卖这两单','after_school',{flags:{risk:true}})],{enter:s=>s.cash+=30});
  N('micro_stock',2018,'初三',s=>[has(s,'micro_upgrade')?'升级包到了。\n里面有更多面膜。':'三箱面膜到了。','同学一开始还会问价格。\n后来有人看见你发消息，就关了聊天框。','上家说，再拿一批利润会更高。'],[C('不再拿货','after_school',{flags:{scammed:true,risk:true}}),C('先把手里的慢慢卖','after_school',{study:-1,flags:{micro:true}})]);
  N('scam_first',2018,'初三',['第一单5块。\n第二单12块。\n都到账了。','第三单需要垫398。'],[C('垫398','scam_locked',{cash:-398},s=>s.cash>=398),C('先退出','after_school',{flags:{risk:true}})],{enter:s=>s.cash+=17});
  N('scam_locked',2018,'初三',['你点了提现。','对方发来一张新的任务单。\n还要再垫钱。','“任务没有完成，暂时不能提现。”'],[C('不补了','after_school',{flags:{scammed:true,risk:true}}),C('找姐姐商量','after_school',{flags:{scammed:true,sister:true,risk:true}},s=>has(s,'sister')),C('再补一单','scam_repeat',{debt:398,flags:{scammed:true}},s=>has(s,'sister')||has(s,'friend'))]);
  N('scam_repeat',2018,'初三',['新单也显示完成。','钱还是提不出来。\n对方头像灰了。'],[C('留下聊天记录','after_school',{flags:{scammed:true,risk:true,scam_records:true}})]);
  N('after_school',2018,'初三',['卷子摊在桌上。','手机里还有没读的消息。\n明天要早起。'],[C('先睡，准备中考','exam',{study:1}),C('看看淘宝购物车','lipstick_student'),C('刷一会儿抖音','screen')]);
  N('lipstick_student',2018,'初三',['淘宝购物车里有一支圣罗兰。\n398。','你看了三天。'],[C('买下来','exam',{cash:-398,flags:{early_lipstick:true}},s=>s.cash>=398),C('先放着','exam',{flags:{early_cart:true}})]);
  N('screen',2018,'初三',['你第一次刷抖音。','有人做美甲，一个月两万。\n有人拍日常，也能挣钱。\n有人说，女人一定要经济独立。','不知不觉，十二点了。'],[C('搜搜怎么拍视频','exam',{learn:1,flags:{internet:true}}),C('搜美甲学徒','exam',{flags:{beauty:true}}),C('睡觉，明天考试','exam',{study:1})]);
  N('exam',2019,'初中毕业生',s=>['成绩出来了。',s.study>0?'普高能上。\n县里的中专也在招生。':'普高的学费还差一些。\n县里的中专也在招生。','中专宣传册上写着：\n毕业推荐就业。'],[C('去普高','high_fee',{flags:{highschool:true}}),C('中专读电商','voc_room',{flags:{vocational:true,ecom:true}}),C('中专读计算机','voc_room',{flags:{vocational:true,computer_major:true},learn:1}),C('先去挣钱','factory',{flags:{left_school:true}})]);
  N('high_fee',2019,'高一',['资料费680。\n老师催了三次。','第四次是在全班面前。\n你把头低下去。','那天放学，你走得很慢。'],[C('明天继续去','aid',{study:1}),C('找姐姐借一点','aid',{flags:{sister:true}},s=>has(s,'sister')),C('不去了','factory',{flags:{left_school:true}})]);
  N('aid',2019,'高一',['学校有助学金。\n需要材料、盖章，还要父母配合。','爸爸说没空。','办公室的灯还亮着。'],[C('找班主任','aid_result',{study:1,flags:{teacher:true}}),C('自己跑材料','aid_result',{study:1,learn:1}),C('算了，周末多干一天','lessons',{cash:160,flags:{parttime:true}})]);
  N('aid_result',2019,'高一',['材料补了两次。\n最后批下来了。','资料费交清。\n生活费还剩一点。','你把回执夹进语文书。'],[C('回教室','lessons',{cash:500})]);
  N('lessons',2020,'高二',['上课换到了手机里。\n家里只有一部屏幕完整的手机。','弟弟也要用。\n你听到一半，掉线了。'],[C('借同学的笔记补','exam_result',{study:1,flags:{classmate:true}}),C('自己找回放','exam_result',{study:1,learn:1}),C('晚上再听一遍','exam_result',{study:1}),C('白天先去做工','exam_result',{cash:600,study:-1})]);
  N('exam_result',2021,'高中毕业生',s=>['高考结束。',s.study>=3?'分数够一所普通本科。':'分数够专科，也够一所民办本科。','你第一次认真查学费、专业和城市。'],[C('读普通本科','tuition_public',{flags:{university:true}},s=>s.study>=3),C('读专科','tuition_public',{flags:{college:true}}),C('读民办本科','tuition_private',{flags:{private:true}}),C('先去工作','factory')]);
  N('voc_room',2019,'中专生',['六人寝。\n一张桌子放电脑，另一张放化妆镜。','有人想单招。\n有人准备去杭州。','老师问你，要不要试试技能大赛。'],[C('报名训练','contest',{flags:{teacher:true},learn:1}),C('晚上自己练','voc_admission',{learn:1}),C('跟着学校去实习','factory')]);
  N('contest',2020,'技能大赛训练队',['你练了几个月。\n搭档临时退出了。','老师重新安排了人。\n你们进了市赛。','省赛在另一个城市。\n路费、住宿，先自己垫。'],[C('问老师借路费','contest_result',{flags:{teacher:true,certificate:true}}),C('拿出自己的钱','contest_result',{cash:-300,flags:{certificate:true}},s=>s.cash>=300),C('今年算了，准备升学','voc_admission',{study:1})]);
  N('contest_result',2021,'中专毕业生',['省赛二等奖。','证书上有你的名字。\n老师在群里发了照片。','你把借的路费还了。\n剩下的奖学金放进银行卡。'],[C('准备单招','voc_admission',{study:1,learn:1}),C('带着证书找工作','factory')],{enter:s=>s.cash+=1000,object:'省赛二等奖'});
  N('voc_admission',2021,'准备升学',s=>settledSister(s)?['你已经离开学校几年了。','姐姐问，你还打算去哪里找工作。']:['单招材料摊在桌上。\n姐姐问你还要读多久。','招生老师把学费和住宿费圈出来。'],[C('报专科','tuition_public',{flags:{college:true}},s=>!settledSister(s)),C('还是先工作','factory')]);
  N('tuition_public',2021,'大学新生',['录取通知书到了。\n学费、住宿费、路费，凑在一起。','学校发来资助说明。\n你从头看了一遍。'],[C('申请助学贷款，暑假打工','summer_tea',{debt:8000,flags:{student_loan:true}}),C('和姐姐一起凑','summer_tea',{flags:{sister:true},debt:5000})]);
  N('tuition_private',2021,'民办本科新生',['学费一年两万多。\n妈妈说，家里出不起。','暑假还有六十天。','你把能申请的资助和缺口写在纸上。'],[C('贷款，再打暑假工','summer_tea',{debt:20000,flags:{student_loan:true}}),C('先工作，明年再想','factory',{flags:{private:false}})]);
  N('summer_tea',2021,'暑假工',['奶茶店招暑假工。\n食堂也招。','都要站一整天。\n食堂包一顿饭。'],[C('去奶茶店','first_wage',{flags:{tea:true}}),C('去食堂','first_wage',{flags:{canteen:true,resource:true}})]);
  N('first_wage',2021,'暑假工',s=>[has(s,'tea')?'你记住了十几种配方。\n手上总有一点糖浆。':'你收餐盘，擦桌子。\n阿姨留了一份饭给你。',has(s,'tea')?'暑假结束，结清了工资。':'阿姨说，开学可以问问勤工助学。','交完剩余费用。\n你留了1200块生活费。'],[C('去学校','lipstick')],{enter:s=>s.cash+=1200});
  N('factory',2021,'电子厂工人',s=>[has(s,'certificate')?'招聘的人看到证书。\n把你的简历又翻了一遍。\n安排了设备辅助岗。':'初中毕业的、中专毕业的。\n还有来实习的大学生。\n站在同一条线上。','上夜班的时候，你看不见天亮。'],[C('先攒钱','work_savings',{flags:{factory:true}}),C('下班记一点东西','work_savings',{flags:{factory:true,creator:true},learn:1})]);
  N('work_savings',2023,'打工者',['两年多。\n扣掉吃住和寄回家的钱，你攒下一点。','妈妈打电话。\n弟弟要买电脑。'],[C('接电话','brother_computer')],{enter:s=>s.cash+=9000});
  N('lipstick',2022,'在校大学生',['淘宝购物车里有一支圣罗兰。\n398。\n你看了三天。','这个月的生活费刚到账。'],[C('买','lipstick_arrive',{cash:-398,flags:{lipstick:true}},s=>s.cash>=398),C('先放着','campus',{flags:{cart:true}})],{object:'购物车 / 1件商品'});
  N('lipstick_arrive',2022,'在校大学生',['快递到了。\n你对着宿舍的小镜子涂了一点。','晚上吃饭前，又擦掉了。\n舍不得。'],[C('把盖子盖好','campus')],{object:'圣罗兰口红'});
  N('campus',2022,'在校大学生',s=>[has(s,'canteen')?'你问到了勤工助学。\n每个月有一笔不大的收入。':'晚上没课的时候，你出去做兼职。','宿舍有人发穿搭。\n有人卖零食。\n有人在二手平台收电脑。'],[C('写写自己的生活','campus_posts',{flags:{creator:true},learn:1}),C('做宿舍小生意','campus_savings',{flags:{business:true}}),C('问问二手电脑','computer',{learn:1}),C('先把课上完','campus_savings',{study:1})]);
  N('campus_posts',2022,'在校大学生',['写了三个小时。\n十三个赞。','其中两个是室友点的。\n一个是你自己。','第二天，还要去上课。'],[C('继续写','computer',{learn:1,flags:{creator:true}}),C('有空再发','campus_savings',{flags:{creator:true}})]);
  N('computer',2022,'在校大学生',['同学有一台旧笔记本。\n风扇响，键盘完好。\n900。','你搜了型号，又借来试了一个晚上。'],[C('买下来','campus_savings',{cash:-900,flags:{computer:true}},s=>s.cash>=900),C('先用机房的','campus_savings',{learn:1,flags:{lab:true}})]);
  N('campus_savings',2023,'在校大学生',['又过了一年。\n零工、补助，或者一笔一笔的小生意。','除去生活费，存下1800。','手机响了。\n妈妈说，弟弟要买电脑。'],[C('接电话','brother_computer')],{enter:s=>s.cash+=1800});
  N('brother_computer',2023,'',s=>[has(s,'gave500')?'“你以前不是也帮他补过课嘛。”':'弟弟发来了一张配置截图。','还差3000。',has(s,'computer')?'你自己的电脑，开机要等两分钟。':'你把自己的余额看了一遍。'],[C('给他3000','brother_thanks',{cash:-3000,family:1,flags:{brother_pc:true}},s=>s.cash>=3000),C('只出1000','brother_thanks',{cash:-1000,family:1,flags:{brother_pc:true}},s=>s.cash>=1000),C('让他自己凑','after_computer',{flags:{boundary:true,pc_refused:true}})]);
  N('brother_thanks',2023,'',['弟弟给你发了三条语音。\n真的很高兴。','他说，以后挣钱了给你换一个好的。','你回了一个表情。'],[C('放下手机','after_computer')]);
  N('after_computer',2024,'',s=>[has(s,'pc_refused')?'妈妈有几天没给你打电话。\n弟弟最后买了一台便宜一些的。':'弟弟的新电脑到了。\n他把照片发在家庭群。',college(s)?'学校开始安排实习。':'厂里又来了新的一批人。',has(s,'certificate')?'你的证书复印件，还夹在资料袋里。':'你更新了一次简历。'],[C('按安排去','internship'),C('自己查招聘','internship',{learn:1,flags:{researched:true}})]);
  N('internship',2024,'实习 / 工作',s=>[college(s)?'读了几年。\n实习招聘里，还是有那家电子厂。':'你想换一份工作。\n招聘信息翻了几页。','杭州有一家电商公司招助播和中控。\n县里的连锁店也缺人。'],[C('去杭州面试','hangzhou_offer',{flags:{ecom:true}}),C('去连锁奶茶店','work_start',{flags:{tea:true}}),C('试试行政岗位','work_start',{flags:{admin:true}},s=>college(s)),C('先留在厂里','work_start',{flags:{factory:true}})]);
  N('hangzhou_offer',2024,'准备去杭州',s=>['车票、押金、第一个月生活费。',has(s,'stash')?'收行李时，你摸到旧棉袄里面的五百块。\n还是那五张。':'你又看了一次余额。','同学说，她的房间可以暂时挤一挤。'],[C('拿那500买车票','work_start',{cash:272,flags:{stash:false,used_stash:true,hangzhou:true}},s=>has(s,'stash')),C('自己付车票','work_start',{cash:-228,flags:{hangzhou:true}},s=>s.cash>=228),C('找同学借路费','work_start',{debt:228,flags:{hangzhou:true}}),C('留在本地','work_start',{flags:{tea:true,ecom:false}})]);
  N('work_start',2025,'上班族',s=>[has(s,'hangzhou')?'客服、中控、助播。\n最初几个月，天天有人喊你的名字。':has(s,'admin')?'行政。工资4200。\n房租1500。':'排班。交接。打卡。\n领工资。',has(s,'certificate')?'你后来听见主管说，面试时记得你那张证书。':'你把第一笔正式工资记在手机里。','吃住、还款、寄钱。\n一年下来，还留住了6000。'],[C('继续','wish22')],{enter:s=>{s.cash+=6000;s.role=has(s,'hangzhou')?'电商中控':has(s,'admin')?'行政':has(s,'tea')?'奶茶店店员':'电子厂工人';}});
  N('wish22',2025,'',['你二十二岁。','你现在想过什么样的日子？'],[C('多挣一点','training',{wish:'多挣一点'}),C('有个自己的住处','training',{wish:'有个自己的住处'}),C('少欠一点','training',{wish:'少欠一点'}),C('做点自己的东西','training',{wish:'做点自己的东西',learn:1,flags:{wants_create:true}})]);
  N('training',2025,'',s=>['零经验新媒体运营。\n月薪8000—12000。','面试的人说，你能力还差一点。\n可以先参加培训。\n19800，分期。',has(s,'scammed')?'“先完成任务，后面才能拿钱。”\n你想起了初中那个聊天框。':'对方把合同推了过来。'],[C('签字','training_result',{debt:19800,flags:{training_debt:true}}),C('把合同带走看看','training_leave',{learn:1,flags:{risk:true}}),C('走','training_leave',{flags:{risk:true}})]);
  N('training_result',2025,'待业',['课上完了。\n推荐的岗位，底薪比广告里低。','还款日倒是写得很清楚。','奶茶店以前的同事问，你要不要回来。'],[C('回去上班','creator_offer',{flags:{tea:true}}),C('继续投简历','creator_offer')]);
  N('training_leave',2025,'上班族',['对方没有再联系你。','原来的工作还在。\n工资也还是原来那些。'],[C('去上班','creator_offer')]);
  N('creator_offer',2026,'',s=>[has(s,'creator')?'你还在更新自己的账号。\n有一篇又是十三个赞。':'晚上，刷到一个人做的小网页。','他在评论里说，是用AI一点点改出来的。',has(s,'computer')?'你的电脑就在桌上。':'二手平台上，900块的旧电脑还很多。'],[C('打开自己的电脑试试','ai_first',{},creative),C('买一台，试试看','ai_first',{cash:-900,flags:{computer:true}},s=>college(s)&&has(s,'creator')&&s.learn>=2&&s.debt<30000&&!has(s,'computer')&&s.cash>=900),C('把链接收好，先去上班','family_rent'),C('搜怎么做，暂时没空','family_rent',{learn:1})]);
  N('ai_first',2026,'上班 / 做项目',['最开始，你只用AI改句子。\n后来，你打开了编辑器。','第一个页面很丑。\n还有三个按钮点不了。'],[C('继续改','ai_again'),C('明天要上班，先睡','family_rent')],{object:'localhost'});
  N('ai_again',2026,'上班 / 做项目',['第二天。\n还是点不了。','你把报错复制进去。\n这回先只改一个按钮。'],[C('再试一次','ai_button'),C('留到以后','family_rent')]);
  N('ai_button',2026,'上班 / 做项目',['那个按钮能用了。','你点了好几次。','屋子里没有别人。'],[C('把小工具发出去','ai_message',{flags:{ai_project:true}})],{object:'第一个按钮'});
  N('ai_message',2026,'上班 / 做项目',['你做了一个小网页。\n又改了一个小游戏。','有人说没用。\n有人说看不懂。','有一条私信，你看了两遍。'],[C('继续做','end_unfinished'),C('白天上班，晚上做','end_unfinished'),C('先去找稳定工作','family_rent')],{quote:'“我以前没这么想过。”'});
  E('end_unfinished',2026,'还没写完',['你二十三岁。\n电脑上还有一个没有做完的项目。','明天。\n你准备继续改。','以前，你一直在别人给你的选项里选。\n后来，你开始自己做按钮。']);
  N('family_rent',2026,'上班族',s=>['你想换一个不用和陌生人合住的房间。','押金、搬家费，算了很久。',has(s,'used_stash')?'当年五百块够你坐车过来。\n这一次，要多攒几个月。':has(s,'stash')?'那五百块后来一直没动。\n你把它存进了银行卡。':'房东让你想好了再回复。'],[C('搬出去，自己住','family_work',{cash:-2400,flags:{room:true}},s=>s.cash>=2400),C('再合住一年','family_work')],{enter:s=>{if(has(s,'stash')){s.cash+=500;s.flags.stash=false;}}});
  N('family_work',2027,'上班族',s=>[has(s,'tea')?'你开始带新人。\n他们叫你店长。':has(s,'hangzhou')?'你接手了一个小直播间。\n下播后，还要核对退款。':has(s,'admin')?'工资涨到6200。\n工作群多了三个。':'你熟悉每一个工位。\n有新人来，会先问你。','这两年，除去生活费和寄回家的钱，你又存了12000。',s.flags.paid27?`你先还了${s.flags.paid27}。\n剩下的，留给自己。`:'这笔钱暂时还没有别的用途。'],[C('看一眼余额','brother_house')],{enter:s=>{s.cash+=12000;const pay=Math.min(8000,s.debt,s.cash);s.debt-=pay;s.cash-=pay;s.flags.paid27=pay;}});
  N('brother_house',2027,'',s=>['弟弟准备买房。','妈妈说，三个姐姐，一人出一点。',s.family>=2?'她报数字的时候，没有先问你有多少。':'她问，你那边能不能拿出一点。'],[C('出8000','house_reply',{cash:-8000,family:1,flags:{house_help:true}},s=>s.cash>=8000),C('最多出2000','house_reply',{cash:-2000,family:1,flags:{house_help:true}},s=>s.cash>=2000),C('这次不出','house_reply',{flags:{boundary:true,house_no:true}})]);
  N('house_reply',2027,'',s=>[has(s,'house_no')?'妈妈说，你现在只顾自己。\n你很久没打下去一个字。':'弟弟说谢谢。\n他把新房的户型图发给你。','姐姐私下说，她那份也是借的。','你们在电话里安静了一会儿。'],[C('先把自己的日子过下去','wish27')]);
  N('wish27',2030,'上班族',['又过了三年。\n工作、房租、还款、家里的事。','你二十七岁。\n现在想过什么样的日子？'],[C('有一个自己的家','marriage_offer',{wish:'有一个自己的家'}),C('把日子过稳','marriage_offer',{wish:'把日子过稳'}),C('有人一起分担','marriage_offer',{wish:'有人一起分担'}),C('暂时没人找我','marriage_offer',{wish:'暂时没人找我'})],{enter:s=>{s.cash+=18000;const pay=Math.min(s.debt,12000,s.cash);s.debt-=pay;s.cash-=pay;}});
  N('marriage_offer',2030,'',s=>[has(s,'love')?'那个给你煮面的人，偶尔还会发消息。\n后来你们去了不同的城市。':'同事给你介绍了一个人。','做销售。收入普通。\n他会做饭。','没有人催你的时候，你们聊得还可以。'],[C('慢慢相处','marriage_later',{flags:{dating:true}}),C('先一个人过','dowry')]);
  N('marriage_later',2030,'恋爱中',['他知道你要给家里钱。\n你也知道他有房贷。','你们把数字摊开。\n商量过日子，也商量不想过的时候怎么办。'],[C('一起过','dowry',{flags:{married:true}}),C('再等等','dowry')]);
  N('dowry',2030,'',s=>['弟弟结婚，还差六万。\n妈妈在电话里哭。',has(s,'brother_pc')?'你想起他收到电脑时发来的语音。':'家庭群里已经发了婚礼日期。',s.family>=2?'“你以前都帮了，就这最后一次。”':'“你弟弟这辈子就这一回。”'],[C('给六万','wedding',{cash:-60000,family:1,flags:{dowry_all:true}},s=>s.cash>=60000),C('借钱补齐六万','wedding',s=>{s.debt+=Math.max(0,60000-s.cash);s.cash=Math.max(0,s.cash-60000);s.family++;s.flags.dowry_all=true;}),C('给一万，剩下自己想办法','wedding',{cash:-10000,family:1,flags:{dowry_part:true}},s=>s.cash>=10000),C('这次不给','wedding',{flags:{dowry_no:true,boundary:true}})]);
  N('wedding',2030,'',s=>['婚礼很热闹。',has(s,'dowry_no')?'妈妈没有让你坐在她旁边。\n弟弟给你留了一份喜糖。':'弟弟忙了一天。\n送你出门时，说以后一定还你。','回去的车上，你打开了银行软件。',s.debt?`还有${s.debt.toLocaleString('zh-CN')}块没还。`:'余额没有变。'],[C('锁上手机','childcare')],{object:'红色结婚请柬'});
  N('childcare',2031,'',s=>['弟媳生了孩子。\n妈妈腰不好。\n弟媳要回去工作。','他们问，你能不能回来几个月。',has(s,'sister')?'姐姐也说，你以前就会带孩子。':'“就半年。”'],[C('请长假回去','care_month',{flags:{caregiver:true}}),C('出两千，请人帮忙','parents',{cash:-2000},s=>s.cash>=2000),C('我不能停下工作','parents',{flags:{boundary:true}})]);
  N('care_month',2031,'回家帮忙',['公司没有批半年假。\n你办了离职。','三个月。六个月。\n家里找不到接手的人。','弟媳下班回来，也很累。'],[C('再帮一阵','end_halfyear'),C('让大家重新安排，我要找工作','return_work',{flags:{caregiver:false,career_gap:true}})]);
  E('end_halfyear',2033,'半年',['你本来只准备帮半年。','后来孩子上幼儿园了。','你在求职表上填最近一份工作。\n想了很久。']);
  N('return_work',2032,'重新找工作',['简历空了一年。\n面试的人问，你这一年做了什么。','旧同事说，可以先回来顶班。'],[C('从头做','parents',{flags:{tea:true}})]);
  N('parents',2032,'',s=>['爸爸住院。\n妈妈干不动了。','四个孩子又建了一个群。',has(s,'brother_pc')?'弟弟先转了一笔钱。\n他说，这次他来出一些。':'大姐把费用拍进群里。',has(s,'sister')?'姐姐给你打电话，说可以轮流。':'群里问，谁能先回来。'],[C('商量四个人轮流','parents_after',{flags:{shared_care:true}},s=>has(s,'sister')||has(s,'brother_pc')||has(s,'boundary')),C('再回去照顾','parents_after',{flags:{caregiver:true}}),C('先寄一笔钱，保住工作','parents_after',{cash:-3000},s=>s.cash>=3000)]);
  N('parents_after',2032,'',s=>[has(s,'shared_care')?'排班表改了三次。\n至少这次写了四个人的名字。':has(s,'caregiver')?'陪护床很窄。\n领导问你什么时候回来。':'钱转过去了。\n晚上妈妈又打来电话。','第二天，闹钟还是六点半。'],[C('起床','last_wish')]);
  N('last_wish',2033,'',s=>['你三十岁。',has(s,'lipstick')?'搬家的箱子里，有那支圣罗兰。\n已经用完了。':has(s,'cart')?'你换过两次手机。\n购物车里已经找不到那支口红。':'旧棉袄早就不穿了。','现在，你想过什么样的日子？'],[C('继续这样也行','settle',{wish:'继续这样也行'}),C('给自己多留一点','settle',{wish:'给自己多留一点'}),C('还想试点别的','settle',{wish:'还想试点别的'})],{enter:s=>{if(!has(s,'caregiver'))s.cash+=6800;const payment=Math.min(6000,s.debt,s.cash);s.cash-=payment;s.debt-=payment;}});
  N('settle',2033,'',s=>[s.debt?`每月还要还款。\n剩余${s.debt.toLocaleString('zh-CN')}。`:'你又检查了一次下个月的账。',has(s,'caregiver')?'家里还需要人。':has(s,'married')?'门打开了。\n厨房有炒菜的声音。':has(s,'hangzhou')?'直播间关了灯。\n楼下还打得到车。':'明天照常上班。'],[C('去上班','end_poor',{},s=>s.debt>0||has(s,'caregiver')),C('进厨房看看','dinner',{},s=>s.debt===0&&!has(s,'caregiver')&&has(s,'married')),C('回家','end_binjiang',{},s=>s.debt===0&&!has(s,'caregiver')&&!has(s,'married')&&has(s,'hangzhou')),C('设好闹钟','end_normal',{},s=>s.debt===0&&!has(s,'caregiver')&&!has(s,'married')&&!has(s,'hangzhou'))]);
  N('dinner',2033,'已婚 / 上班族',['他做了两个菜。\n问你饭够不够。','冰箱上贴着轮流做饭的排班表。','你拍了一张照片。'],[C('发到网上','comments'),C('放下手机吃饭','end_home')]);
  N('comments',2033,'已婚 / 上班族',['配文：\n下班回家有人烧饭。','评论区有人祝你幸福。\n有人骂你娇妻。\n有人说你没有主体性。','消息还在增加。'],[C('删掉','end_wife'),C('回骂','end_wife'),C('不管','end_wife')]);
  E('end_second_mother',2021,'第二个妈妈',['你十八岁。\n你已经会照顾一个孩子了。','简历上。\n工作经验：无。']);
  E('end_poor',2033,'贫穷的大女主',['手机里的人说，大女主要永远先爱自己。','第二天。\n六点半。','你起床上班。']);
  E('end_binjiang',2033,'滨江夜班',['凌晨两点。\n你下班了。','你已经很久没向家里要钱。','电梯里只有你。\n明天不用早起。']);
  E('end_home',2033,'普通人的家',['房贷。工作。\n轮流做家务。','今天他做饭。\n明天你早下班。','饭还热着。']);
  E('end_wife',2033,'围剿的娇妻',['你还在看评论。','丈夫从厨房问：','“明天还吃这个吗？”']);
  E('end_normal',2033,'什么也没有发生',s=>['你避开了一些事。\n也错过了一些事。','没有暴富。\n没有传奇。',`三十岁。\n存款${s.cash.toLocaleString('zh-CN')}。`,'今天还是周一。']);
  window.STORY = { nodes, endings, fresh, apply, has, college, creative, C, N, E };
})();
